name: Update QR codes

on:
  push:
    branches:
      - master

jobs:
  check_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate QR Codes
        run: |
          pip3 install pypng==0.20220715.0
          pip3 install PyQRCode==1.2.1
          utils/generate_qr_codes.py
